module.exports = {
    worksheetConfig: {
        "addition-sums-within-10": {
            title: "Addition Sums Within 10 - Grade 1 Math Worksheets",
            description: "Free printable addition worksheets for sums up to 10. Perfect for Grade 1 students learning basic addition facts.",
            icon: "➕",
            type: "addition",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-11-23"
        },
        "addition-sums-within-10-practice": {
            title: "Addition Practice Within 10 - Kindergarten & Grade 1",
            description: "Simple addition worksheets with sums up to 10. Great for building foundational math skills in early learners.",
            icon: "➕",
            type: "addition",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-11-24"
        },
        "addition-sums-to-10-vertical": {
            title: "Vertical Addition Sums to 10 - Grade 1 Worksheets",
            description: "Vertical format addition problems with sums up to 10. Helps students practice proper number alignment.",
            icon: "➕",
            type: "addition",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-11-25"
        },
        "addition-sums-within-20": {
            title: "Addition Sums Within 20 - Grade 1 & 2 Math Practice",
            description: "Free addition worksheets for sums up to 20. Perfect for Grade 1 and Grade 2 students mastering basic addition.",
            icon: "➕",
            type: "addition",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2025-11-26"
        },
        "addition-sums-to-20-practice": {
            title: "Addition Practice Sums to 20 - Grade 2 Worksheets",
            description: "Comprehensive addition practice sheets with sums up to 20. Builds confidence in Grade 2 math skills.",
            icon: "➕",
            type: "addition",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2025-11-27"
        },
        "addition-doubles-facts": {
            title: "Addition Doubles Facts Worksheets - Grade 1 & 2",
            description: "Practice addition doubles facts (2+2, 3+3, etc.) with these free printable worksheets for early elementary students.",
            icon: "➕",
            type: "addition",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-11-28"
        },
        "addition-near-doubles": {
            title: "Near Doubles Addition Worksheets - Grade 2 Math",
            description: "Learn near doubles addition strategies (2+3, 4+5) with these engaging worksheets for Grade 2 students.",
            icon: "➕",
            type: "addition",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-11-29"
        },
        "addition-two-digit-no-regrouping": {
            title: "Two-Digit Addition No Regrouping - Grade 2 Worksheets",
            description: "Two-digit addition problems without regrouping. Perfect for Grade 2 students learning multi-digit addition.",
            icon: "➕",
            type: "addition",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50],
            counts: [10, 20, 30],
            releaseDate: "2025-11-30"
        },
        "addition-two-digit-horizontal": {
            title: "Horizontal Two-Digit Addition - Grade 2 Practice",
            description: "Horizontal format two-digit addition worksheets. Helps students understand place value in addition.",
            icon: "➕",
            type: "addition",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50],
            counts: [10, 20, 30],
            releaseDate: "2025-12-01"
        },
        "addition-two-digit-vertical": {
            title: "Vertical Two-Digit Addition - Grade 2 Math Sheets",
            description: "Vertical two-digit addition worksheets without regrouping. Essential practice for Grade 2 mathematics.",
            icon: "➕",
            type: "addition",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50],
            counts: [10, 20, 30],
            releaseDate: "2025-12-02"
        },
        "addition-missing-addends": {
            title: "Missing Addends Addition Worksheets - Grade 1 & 2",
            description: "Find the missing addend in addition problems. Develops number sense and algebraic thinking in early grades.",
            icon: "➕",
            type: "addition",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2025-12-03"
        },
        "addition-word-problems-grade1": {
            title: "Addition Word Problems Grade 1 - Story Problems",
            description: "Simple addition word problems for Grade 1. Helps students apply addition skills to real-world situations.",
            icon: "➕",
            type: "addition",
            defaultRange: 20,
            defaultCount: 10,
            ranges: [10, 20],
            counts: [5, 10],
            releaseDate: "2025-12-04"
        },
        "addition-speed-drills-10": {
            title: "Addition Speed Drills Sums to 10 - Timed Practice",
            description: "Timed addition speed drills with sums up to 10. Builds fluency and automaticity in basic addition facts.",
            icon: "➕",
            type: "addition",
            defaultRange: 10,
            defaultCount: 30,
            ranges: [5, 10],
            counts: [20, 30],
            releaseDate: "2025-12-05"
        },
        "addition-speed-drills-20": {
            title: "Addition Speed Drills Sums to 20 - Grade 2 Practice",
            description: "Timed addition speed drills with sums up to 20. Perfect for building quick recall of addition facts.",
            icon: "➕",
            type: "addition",
            defaultRange: 20,
            defaultCount: 30,
            ranges: [10, 20],
            counts: [20, 30],
            releaseDate: "2025-12-06"
        },
        "addition-review-grade1-2": {
            title: "Addition Review Grade 1 & 2 - Mixed Practice",
            description: "Comprehensive addition review worksheets mixing sums within 10 and 20. Perfect end-of-unit practice.",
            icon: "➕",
            type: "addition",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2025-12-07"
        },
        "subtraction-within-10": {
            title: "Subtraction Within 10 - Grade 1 Math Worksheets",
            description: "Free printable subtraction worksheets for differences within 10. Perfect for Grade 1 students learning basic subtraction.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-12-08"
        },
        "subtraction-within-10-practice": {
            title: "Subtraction Practice Within 10 - Kindergarten & Grade 1",
            description: "Simple subtraction worksheets with differences within 10. Great for building foundational math skills in early learners.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-12-09"
        },
        "subtraction-within-10-vertical": {
            title: "Vertical Subtraction Within 10 - Grade 1 Worksheets",
            description: "Vertical format subtraction problems within 10. Helps students practice proper number alignment and borrowing concepts.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-12-10"
        },
        "subtraction-within-20": {
            title: "Subtraction Within 20 - Grade 1 & 2 Math Practice",
            description: "Free subtraction worksheets for differences within 20. Perfect for Grade 1 and Grade 2 students mastering basic subtraction.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2025-12-11"
        },
        "subtraction-within-20-practice": {
            title: "Subtraction Practice Within 20 - Grade 2 Worksheets",
            description: "Comprehensive subtraction practice sheets within 20. Builds confidence in Grade 2 math skills and number relationships.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2025-12-12"
        },
        "subtraction-within-100": {
            title: "Subtraction Within 100 - Grade 2 Math Worksheets",
            description: "Two-digit subtraction worksheets within 100. Perfect for Grade 2 students learning multi-digit subtraction without regrouping.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 100,
            defaultCount: 20,
            ranges: [50, 100],
            counts: [10, 20, 30],
            releaseDate: "2025-12-13"
        },
        "subtraction-two-digit-no-regrouping": {
            title: "Two-Digit Subtraction No Regrouping - Grade 2 Practice",
            description: "Two-digit subtraction problems without regrouping. Essential practice for Grade 2 students learning place value subtraction.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 100,
            defaultCount: 20,
            ranges: [50, 100],
            counts: [10, 20, 30],
            releaseDate: "2025-12-14"
        },
        "subtraction-two-digit-horizontal": {
            title: "Horizontal Two-Digit Subtraction - Grade 2 Worksheets",
            description: "Horizontal format two-digit subtraction worksheets. Helps students understand place value in subtraction operations.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 100,
            defaultCount: 20,
            ranges: [50, 100],
            counts: [10, 20, 30],
            releaseDate: "2025-12-15"
        },
        "subtraction-two-digit-vertical": {
            title: "Vertical Two-Digit Subtraction - Grade 2 Math Sheets",
            description: "Vertical two-digit subtraction worksheets without regrouping. Essential practice for Grade 2 mathematics curriculum.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 100,
            defaultCount: 20,
            ranges: [50, 100],
            counts: [10, 20, 30],
            releaseDate: "2025-12-16"
        },
        "subtraction-missing-subtrahend": {
            title: "Missing Subtrahend Subtraction - Grade 1 & 2 Worksheets",
            description: "Find the missing subtrahend in subtraction problems. Develops number sense and algebraic thinking in early grades.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2025-12-17"
        },
        "subtraction-word-problems-grade1": {
            title: "Subtraction Word Problems Grade 1 - Story Problems",
            description: "Simple subtraction word problems for Grade 1. Helps students apply subtraction skills to real-world situations and contexts.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 20,
            defaultCount: 10,
            ranges: [10, 20],
            counts: [5, 10],
            releaseDate: "2025-12-18"
        },
        "subtraction-speed-drills-10": {
            title: "Subtraction Speed Drills Within 10 - Timed Practice",
            description: "Timed subtraction speed drills within 10. Builds fluency and automaticity in basic subtraction facts for early learners.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 10,
            defaultCount: 30,
            ranges: [5, 10],
            counts: [20, 30],
            releaseDate: "2025-12-19"
        },
        "subtraction-speed-drills-20": {
            title: "Subtraction Speed Drills Within 20 - Grade 2 Practice",
            description: "Timed subtraction speed drills within 20. Perfect for building quick recall of subtraction facts in Grade 2 students.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 20,
            defaultCount: 30,
            ranges: [10, 20],
            counts: [20, 30],
            releaseDate: "2025-12-20"
        },
        "subtraction-review-grade1-2": {
            title: "Subtraction Review Grade 1 & 2 - Mixed Practice",
            description: "Comprehensive subtraction review worksheets mixing differences within 10, 20, and 100. Perfect end-of-unit practice.",
            icon: "➖",
            type: "subtraction",
            defaultRange: 100,
            defaultCount: 20,
            ranges: [20, 50, 100],
            counts: [10, 20, 30],
            releaseDate: "2025-12-21"
        },
        "multiplication-times-table-2": {
            title: "2 Times Table Multiplication Worksheets - Grade 3",
            description: "Practice the 2 times table with these free printable multiplication worksheets. Perfect for Grade 3 students learning multiplication.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-22"
        },
        "multiplication-times-table-5": {
            title: "5 Times Table Multiplication Worksheets - Grade 3",
            description: "Master the 5 times table with these engaging multiplication worksheets. Great for Grade 3 students building multiplication fluency.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-23"
        },
        "multiplication-times-table-10": {
            title: "10 Times Table Multiplication Worksheets - Grade 3",
            description: "Learn the 10 times table with these free multiplication worksheets. Perfect for Grade 3 students mastering multiplication patterns.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-24"
        },
        "multiplication-times-table-3": {
            title: "3 Times Table Multiplication Worksheets - Grade 3",
            description: "Practice the 3 times table with these printable multiplication worksheets. Essential for Grade 3 multiplication curriculum.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-25"
        },
        "multiplication-times-table-4": {
            title: "4 Times Table Multiplication Worksheets - Grade 3",
            description: "Master the 4 times table with these free multiplication worksheets. Builds confidence in Grade 3 multiplication skills.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-26"
        },
        "multiplication-times-table-6": {
            title: "6 Times Table Multiplication Worksheets - Grade 3",
            description: "Learn the 6 times table with these engaging multiplication worksheets. Perfect for Grade 3 students advancing in multiplication.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-27"
        },
        "multiplication-times-table-7": {
            title: "7 Times Table Multiplication Worksheets - Grade 3",
            description: "Practice the 7 times table with these printable multiplication worksheets. Essential practice for Grade 3 multiplication mastery.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-28"
        },
        "multiplication-times-table-8": {
            title: "8 Times Table Multiplication Worksheets - Grade 3",
            description: "Master the 8 times table with these free multiplication worksheets. Builds fluency in Grade 3 multiplication facts.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-29"
        },
        "multiplication-times-table-9": {
            title: "9 Times Table Multiplication Worksheets - Grade 3",
            description: "Learn the 9 times table with these engaging multiplication worksheets. Perfect for Grade 3 students completing times tables.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2025-12-30"
        },
        "multiplication-mixed-1-10": {
            title: "Mixed Multiplication 1-10 - Grade 3 Practice Worksheets",
            description: "Mixed multiplication facts from 1 to 10. Comprehensive practice for Grade 3 students mastering all basic multiplication tables.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [5, 10],
            counts: [10, 20, 30],
            releaseDate: "2025-12-31"
        },
        "multiplication-mixed-1-12": {
            title: "Mixed Multiplication 1-12 - Grade 3 & 4 Worksheets",
            description: "Mixed multiplication facts from 1 to 12. Advanced practice for Grade 3 and Grade 4 students completing multiplication mastery.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-01"
        },
        "multiplication-word-problems-grade3": {
            title: "Multiplication Word Problems Grade 3 - Story Problems",
            description: "Multiplication word problems for Grade 3. Helps students apply multiplication skills to real-world situations and problem-solving.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 10,
            ranges: [5, 10, 12],
            counts: [5, 10],
            releaseDate: "2026-01-02"
        },
        "multiplication-speed-drills": {
            title: "Multiplication Speed Drills - Timed Practice Grade 3",
            description: "Timed multiplication speed drills for Grade 3. Builds fluency and automaticity in multiplication facts for quick recall.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 30,
            ranges: [5, 10, 12],
            counts: [20, 30],
            releaseDate: "2026-01-03"
        },
        "multiplication-review-grade3": {
            title: "Multiplication Review Grade 3 - Mixed Practice",
            description: "Comprehensive multiplication review for Grade 3. Mixed practice covering all times tables from 1 to 12 for mastery.",
            icon: "✖️",
            type: "multiplication",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-04"
        },
        "division-whole-numbers-2": {
            title: "Division by 2 Worksheets - Grade 3 & 4 Math",
            description: "Division worksheets with divisor 2. Perfect for Grade 3 and Grade 4 students learning basic division with whole number results.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-05"
        },
        "division-whole-numbers-3": {
            title: "Division by 3 Worksheets - Grade 3 & 4 Practice",
            description: "Division worksheets with divisor 3. Great for Grade 3 and Grade 4 students mastering division facts and whole number quotients.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-06"
        },
        "division-whole-numbers-4": {
            title: "Division by 4 Worksheets - Grade 3 & 4 Math Sheets",
            description: "Division worksheets with divisor 4. Essential practice for Grade 3 and Grade 4 students learning division operations.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-07"
        },
        "division-whole-numbers-5": {
            title: "Division by 5 Worksheets - Grade 3 & 4 Worksheets",
            description: "Division worksheets with divisor 5. Perfect for Grade 3 and Grade 4 students building division fluency and understanding.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-08"
        },
        "division-whole-numbers-6": {
            title: "Division by 6 Worksheets - Grade 3 & 4 Math Practice",
            description: "Division worksheets with divisor 6. Great for Grade 3 and Grade 4 students advancing in division skills and number relationships.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-09"
        },
        "division-whole-numbers-7": {
            title: "Division by 7 Worksheets - Grade 3 & 4 Practice Sheets",
            description: "Division worksheets with divisor 7. Essential practice for Grade 3 and Grade 4 students mastering division facts.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-10"
        },
        "division-whole-numbers-8": {
            title: "Division by 8 Worksheets - Grade 3 & 4 Math",
            description: "Division worksheets with divisor 8. Perfect for Grade 3 and Grade 4 students completing division mastery and fluency.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-11"
        },
        "division-whole-numbers-9": {
            title: "Division by 9 Worksheets - Grade 3 & 4 Practice",
            description: "Division worksheets with divisor 9. Great for Grade 3 and Grade 4 students building advanced division skills.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-12"
        },
        "division-whole-numbers-10": {
            title: "Division by 10 Worksheets - Grade 3 & 4 Math Sheets",
            description: "Division worksheets with divisor 10. Essential practice for Grade 3 and Grade 4 students learning division patterns.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-13"
        },
        "division-whole-numbers-11": {
            title: "Division by 11 Worksheets - Grade 3 & 4 Practice",
            description: "Division worksheets with divisor 11. Perfect for Grade 3 and Grade 4 students mastering all division facts up to 12.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-14"
        },
        "division-whole-numbers-12": {
            title: "Division by 12 Worksheets - Grade 3 & 4 Math",
            description: "Division worksheets with divisor 12. Great for Grade 3 and Grade 4 students completing division mastery through 12.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-15"
        },
        "division-mixed-divisors-2-12": {
            title: "Mixed Division Divisors 2-12 - Grade 3 & 4 Practice",
            description: "Mixed division worksheets with divisors from 2 to 12. Comprehensive practice for Grade 3 and Grade 4 division mastery.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-16"
        },
        "division-word-problems-grade3": {
            title: "Division Word Problems Grade 3 & 4 - Story Problems",
            description: "Division word problems for Grade 3 and Grade 4. Helps students apply division skills to real-world situations and contexts.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 10,
            ranges: [5, 10, 12],
            counts: [5, 10],
            releaseDate: "2026-01-17"
        },
        "division-speed-drills": {
            title: "Division Speed Drills - Timed Practice Grade 3 & 4",
            description: "Timed division speed drills for Grade 3 and Grade 4. Builds fluency and automaticity in division facts for quick recall.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 30,
            ranges: [5, 10, 12],
            counts: [20, 30],
            releaseDate: "2026-01-18"
        },
        "division-review-grade3-4": {
            title: "Division Review Grade 3 & 4 - Mixed Practice",
            description: "Comprehensive division review for Grade 3 and Grade 4. Mixed practice covering all divisors from 2 to 12 for mastery.",
            icon: "➗",
            type: "division",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-01-19"
        },
        "fractions-like-denominators": {
            title: "Fractions with Like Denominators - Grade 3 & 4 Math",
            description: "Fraction worksheets with like denominators. Perfect for Grade 3 and Grade 4 students learning fraction addition and subtraction.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-20"
        },
        "fractions-adding-like-denominators": {
            title: "Adding Fractions Like Denominators - Grade 4 Worksheets",
            description: "Adding fractions with like denominators worksheets. Great for Grade 4 students mastering fraction addition operations.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-21"
        },
        "fractions-subtracting-like-denominators": {
            title: "Subtracting Fractions Like Denominators - Grade 4 Practice",
            description: "Subtracting fractions with like denominators worksheets. Essential practice for Grade 4 students learning fraction subtraction.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-22"
        },
        "fractions-equivalent-fractions": {
            title: "Equivalent Fractions Worksheets - Grade 3 & 4 Math",
            description: "Equivalent fractions practice worksheets. Perfect for Grade 3 and Grade 4 students understanding fraction relationships.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-23"
        },
        "fractions-comparing-fractions": {
            title: "Comparing Fractions Worksheets - Grade 3 & 4 Practice",
            description: "Comparing fractions worksheets using greater than, less than, and equal to. Great for Grade 3 and Grade 4 fraction skills.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-24"
        },
        "fractions-simplifying-fractions": {
            title: "Simplifying Fractions Worksheets - Grade 4 & 5 Math",
            description: "Simplifying fractions to lowest terms worksheets. Essential practice for Grade 4 and Grade 5 students mastering fractions.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-25"
        },
        "fractions-mixed-numbers": {
            title: "Mixed Numbers Fractions Worksheets - Grade 4 & 5",
            description: "Mixed numbers and improper fractions worksheets. Perfect for Grade 4 and Grade 5 students learning fraction conversions.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-26"
        },
        "fractions-adding-mixed-numbers": {
            title: "Adding Mixed Numbers Worksheets - Grade 4 & 5 Practice",
            description: "Adding mixed numbers with like denominators worksheets. Great for Grade 4 and Grade 5 students advancing in fraction operations.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-27"
        },
        "fractions-subtracting-mixed-numbers": {
            title: "Subtracting Mixed Numbers Worksheets - Grade 4 & 5",
            description: "Subtracting mixed numbers with like denominators worksheets. Essential practice for Grade 4 and Grade 5 fraction mastery.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-28"
        },
        "fractions-word-problems": {
            title: "Fraction Word Problems Grade 4 & 5 - Story Problems",
            description: "Fraction word problems for Grade 4 and Grade 5. Helps students apply fraction skills to real-world situations and contexts.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 10,
            ranges: [10, 20],
            counts: [5, 10],
            releaseDate: "2026-01-29"
        },
        "fractions-review-grade4-5": {
            title: "Fraction Review Grade 4 & 5 - Mixed Practice",
            description: "Comprehensive fraction review for Grade 4 and Grade 5. Mixed practice covering all fraction operations for mastery.",
            icon: "🔢",
            type: "fractions",
            defaultRange: 10,
            defaultCount: 20,
            ranges: [10, 20],
            counts: [10, 20, 30],
            releaseDate: "2026-01-30"
        },
        "mixed-operations-addition-subtraction": {
            title: "Mixed Addition and Subtraction - Grade 2 & 3 Math",
            description: "Mixed addition and subtraction worksheets. Perfect for Grade 2 and Grade 3 students practicing both operations together.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20, 50],
            counts: [10, 20, 30],
            releaseDate: "2026-01-31"
        },
        "mixed-operations-multiplication-division": {
            title: "Mixed Multiplication and Division - Grade 3 & 4 Practice",
            description: "Mixed multiplication and division worksheets. Great for Grade 3 and Grade 4 students practicing both operations together.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 12,
            defaultCount: 20,
            ranges: [5, 10, 12],
            counts: [10, 20, 30],
            releaseDate: "2026-02-01"
        },
        "mixed-operations-all-four": {
            title: "Mixed Operations All Four - Grade 3 & 4 Math Worksheets",
            description: "Mixed addition, subtraction, multiplication, and division worksheets. Comprehensive practice for Grade 3 and Grade 4 students.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20, 50],
            counts: [10, 20, 30],
            releaseDate: "2026-02-02"
        },
        "mixed-operations-word-problems": {
            title: "Mixed Operations Word Problems - Grade 3 & 4 Story Problems",
            description: "Mixed operations word problems for Grade 3 and Grade 4. Helps students apply all four operations to real-world situations.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 20,
            defaultCount: 10,
            ranges: [10, 20, 50],
            counts: [5, 10],
            releaseDate: "2026-02-03"
        },
        "mixed-operations-speed-drills": {
            title: "Mixed Operations Speed Drills - Timed Practice Grade 3 & 4",
            description: "Timed mixed operations speed drills for Grade 3 and Grade 4. Builds fluency in all four operations for quick recall.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 20,
            defaultCount: 30,
            ranges: [10, 20, 50],
            counts: [20, 30],
            releaseDate: "2026-02-04"
        },
        "mixed-operations-challenge-grade3": {
            title: "Mixed Operations Challenge Grade 3 - Advanced Practice",
            description: "Challenging mixed operations worksheets for Grade 3. Advanced practice combining all four operations for mastery.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20, 50],
            counts: [10, 20, 30],
            releaseDate: "2026-02-05"
        },
        "mixed-operations-challenge-grade4": {
            title: "Mixed Operations Challenge Grade 4 - Advanced Worksheets",
            description: "Challenging mixed operations worksheets for Grade 4. Advanced practice with larger numbers and complex problems.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50, 100],
            counts: [10, 20, 30],
            releaseDate: "2026-02-06"
        },
        "mixed-operations-timed-practice": {
            title: "Timed Mixed Operations Practice - Grade 3 & 4 Speed Tests",
            description: "Timed practice sheets for mixed operations. Perfect for Grade 3 and Grade 4 students building speed and accuracy.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 20,
            defaultCount: 30,
            ranges: [10, 20, 50],
            counts: [20, 30],
            releaseDate: "2026-02-07"
        },
        "mixed-operations-review-grade3": {
            title: "Mixed Operations Review Grade 3 - Comprehensive Practice",
            description: "Comprehensive mixed operations review for Grade 3. Covers all four operations with varied difficulty levels.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 20,
            defaultCount: 20,
            ranges: [10, 20, 50],
            counts: [10, 20, 30],
            releaseDate: "2026-02-08"
        },
        "mixed-operations-review-grade4": {
            title: "Mixed Operations Review Grade 4 - Comprehensive Worksheets",
            description: "Comprehensive mixed operations review for Grade 4. Advanced practice covering all operations with larger numbers.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50, 100],
            counts: [10, 20, 30],
            releaseDate: "2026-02-09"
        },
        "mixed-operations-final-challenge": {
            title: "Final Mixed Operations Challenge - Grade 3 & 4 Mastery",
            description: "Final challenge worksheets combining all four operations. Perfect end-of-unit assessment for Grade 3 and Grade 4 mastery.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50, 100],
            counts: [10, 20, 30],
            releaseDate: "2026-02-10"
        },
        "mixed-operations-problem-solving": {
            title: "Mixed Operations Problem Solving - Grade 3 & 4",
            description: "Problem-solving worksheets with mixed operations. Develops critical thinking and application of all four operations in context.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 15,
            ranges: [20, 50, 100],
            counts: [10, 15, 20],
            releaseDate: "2026-02-11"
        },
        "mixed-operations-multi-step": {
            title: "Multi-Step Mixed Operations - Grade 3 & 4 Worksheets",
            description: "Multi-step problems using mixed operations. Advanced practice for Grade 3 and Grade 4 students solving complex problems.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 15,
            ranges: [20, 50, 100],
            counts: [10, 15, 20],
            releaseDate: "2026-02-12"
        },
        "mixed-operations-mental-math": {
            title: "Mental Math Mixed Operations - Grade 3 & 4 Practice",
            description: "Mental math practice with mixed operations. Builds quick calculation skills without paper for Grade 3 and Grade 4 students.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 20,
            defaultCount: 30,
            ranges: [10, 20, 50],
            counts: [20, 30],
            releaseDate: "2026-02-13"
        },
        "mixed-operations-assessment": {
            title: "Mixed Operations Assessment - Grade 3 & 4 Test Prep",
            description: "Comprehensive assessment worksheets for mixed operations. Perfect test preparation for Grade 3 and Grade 4 students.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50, 100],
            counts: [10, 20, 30],
            releaseDate: "2026-02-14"
        },
        "mixed-operations-mastery-final": {
            title: "Mixed Operations Mastery Final - Grade 3 & 4 Complete",
            description: "Final mastery worksheets for all mixed operations. Complete assessment covering all four operations for Grade 3 and Grade 4.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50, 100],
            counts: [10, 20, 30],
            releaseDate: "2026-02-15"
        },
        "mixed-operations-comprehensive-review": {
            title: "Comprehensive Mixed Operations Review - Grade 3 & 4",
            description: "Comprehensive review of all mixed operations. Final practice covering addition, subtraction, multiplication, and division together.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50, 100],
            counts: [10, 20, 30],
            releaseDate: "2026-02-16"
        },
        "mixed-operations-advanced-challenge": {
            title: "Advanced Mixed Operations Challenge - Grade 4 & 5",
            description: "Advanced challenge worksheets with mixed operations. Higher difficulty problems for Grade 4 and Grade 5 students seeking mastery.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 100,
            defaultCount: 20,
            ranges: [50, 100],
            counts: [10, 20, 30],
            releaseDate: "2026-02-17"
        },
        "mixed-operations-real-world-applications": {
            title: "Real-World Mixed Operations Applications - Grade 3 & 4",
            description: "Real-world application problems using mixed operations. Helps students connect math to everyday situations and problem-solving.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 15,
            ranges: [20, 50, 100],
            counts: [10, 15, 20],
            releaseDate: "2026-02-18"
        },
        "mixed-operations-fluency-builder": {
            title: "Mixed Operations Fluency Builder - Grade 3 & 4 Practice",
            description: "Fluency-building worksheets for mixed operations. Develops speed and accuracy in all four operations for Grade 3 and Grade 4.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 30,
            ranges: [20, 50, 100],
            counts: [20, 30],
            releaseDate: "2026-02-19"
        },
        "mixed-operations-90-day-completion": {
            title: "90-Day Mixed Operations Completion - Final Mastery Test",
            description: "Final completion test for 90-day mixed operations mastery. Comprehensive assessment celebrating completion of the full program.",
            icon: "🔀",
            type: "mixed",
            defaultRange: 50,
            defaultCount: 20,
            ranges: [20, 50, 100],
            counts: [10, 20, 30],
            releaseDate: "2026-02-20"
        }
    }
};
